services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  autok3s:
    image: cnrancher/autok3s:v0.4.7
    init: true
    ports:
    - 8080
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $HOME/.autok3s/:$HOME/.autok3s/
    environment:
    - AUTOK3S_CONFIG=$HOME/.autok3s/
    - VIRTUAL_HOST=autok3s.vcap.me
